export const ActionTypes = {
  SET_HOMEPAGE_GALLERY: "SET_HOMEPAGE_GALLERY",
  SET_HOMEPAGE_GALLERY_HAS_ERROR: "SET_HOMEPAGE_GALLERY_HAS_ERROR",
  SET_HOMEPAGE_SEARCH_VALUE: "SET_HOMEPAGE_SEARCH_VALUE",
  
  SET_PHOTOPAGE_IMAGE: "SET_PHOTOPAGE_IMAGE",
  SET_PHOTOPAGE_IMAGES: "SET_PHOTOPAGE_IMAGES",
};
